mod command_line_arguments;
mod taking_user_input;
mod variable_shadowing;
mod type_conversion;
mod array_vector;
mod data_types;
mod conditional_statements;
mod looping;
mod strings_practise;
mod error_handling;
mod functions;
mod tuples;
mod arrays;
mod ownership_borrowing;
mod slicing;
mod structures;
mod enums_options;
mod modules;
mod collections_vector;
mod result_type_error_handling;
mod generics;
mod generics_turbofish;
mod any_all;
mod iterators_chaining;
mod file_handling;
mod traits_interface;
mod closures;
mod iterators;
mod map_filter_collect;
mod box_smart_pointer;
mod threading;
mod tuple_struct;
mod collections_vecdeque;
mod collections_hashmap;
mod time_calculation;
mod stack_heap;
mod lifetimes;
mod external_module;
mod output_formatting;

// hit double shift to search files in pycharm
fn main() {
    command_line_arguments::run();
    taking_user_input::run();
    variable_shadowing::run();
    type_conversion::run();
    array_vector::run();
    data_types::run();
    conditional_statements::run();
    looping::run();
    strings_practise::run();
    error_handling::run();
    functions::run();
    tuples::run();
    tuple_struct::run();
    arrays::run();
    ownership_borrowing::run();
    slicing::run();
    structures::run();
    enums_options::run();
    modules::helper_functions::print_module_name();
    collections_vector::run();
    result_type_error_handling::run();
    generics::run();
    generics_turbofish::run();
    traits_interface::run();
    file_handling::run();
    closures::run();
    iterators::run();
    iterators_chaining::run();
    map_filter_collect::run();
    box_smart_pointer::run();
    threading::run();
    collections_vecdeque::run();
    collections_hashmap::run();
    time_calculation::run();
    stack_heap::run();
    lifetimes::run();
    external_module::run();
    output_formatting::run();
    any_all::run();
}
